## https://nuxtjs.org/faq/github-pages/
language: node_js
node_js:
  - '9'

cache:
  directories:
    - ~/.npm

notifications:
  email:
    recipients:
      - sunxiaofeng@msn.com
    on_success: always
    on_failure: always

git:
  depth: 3
script:
  - yarn deploy-travis-ci
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: out
  target-branch: master
  on:
    branch: develop